export enum WebSocket {
  POST_GET_ALL_DATA = 'POST_GET_ALL_DATA',
  SUBSCRIBE_TO_COMMENT_ROOM = 'SUBSCRIBE_TO_COMMENT_ROOM',
  NEW_COMMENT = 'NEW_COMMENT',
  NEW_REACTION = 'NEW_REACTION',
  DELETE_REACTION = 'DELETE_REACTION',
}
